package com.acuilab.bc.main.wallet;

import com.acuilab.bc.main.nft.MetaData;
import java.awt.Image;
import org.jdesktop.swingx.JXPanel;

import java.net.URL;
import org.jdesktop.swingx.painter.PinstripePainter;
//import org.json.JSONArray;
//import org.json.JSONObject;
/**
 *
 * @author admin
 */
public class ConFiNFTPanel extends JXPanel {

    /**
     * Creates new form NFTPanel
     */
    public ConFiNFTPanel(MetaData metaData) {
	initComponents();
	this.setBackgroundPainter(new PinstripePainter());
        this.idLbl.setText("编号：" + metaData.getId());
        
        
        this.nameLbl.setText("名称：" + metaData.getName());
        this.platformLbl.setText("平台：" + metaData.getPlatform());
        this.descTextArea.setText(metaData.getDesc());
        
        try {
            URL url = new URL(metaData.getImageUrl());
	    this.imageView.setImage(url);
	    Image image = imageView.getImage();
	    double scaleX = 200.0d/image.getWidth(null);
	    double scaleY = 200.0d/image.getHeight(null);
	    System.out.println("scaleX=" + scaleX + ", scaleY=" + scaleY);
            this.imageView.setScale(Math.max(scaleX, scaleY));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        //this.jXImageView1.setImage(urlImage));
        //8016{"body":"000","eye":"013","nose":"001","auxiliary":"001","background":"000","clothes":"006","props":"000","title":"002_000_000_013_001_000_001_000","url":"002_000_000_013_001_000_001_000.png"}
        //http://cdn.tspace.online/image/finish/001_000_000_003_005_001_004_001.png
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new org.jdesktop.swingx.JXLabel();
        idLbl = new org.jdesktop.swingx.JXLabel();
        platformLbl = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTextArea = new org.jdesktop.swingx.JXTextArea();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        imageView = new org.jdesktop.swingx.JXImageView();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(180, 320));
        setMinimumSize(new java.awt.Dimension(180, 320));
        setPreferredSize(new java.awt.Dimension(180, 320));

        org.openide.awt.Mnemonics.setLocalizedText(nameLbl, org.openide.util.NbBundle.getMessage(ConFiNFTPanel.class, "ConFiNFTPanel.nameLbl.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(idLbl, org.openide.util.NbBundle.getMessage(ConFiNFTPanel.class, "ConFiNFTPanel.idLbl.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(platformLbl, org.openide.util.NbBundle.getMessage(ConFiNFTPanel.class, "ConFiNFTPanel.platformLbl.text")); // NOI18N

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        descTextArea.setEditable(false);
        descTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        descTextArea.setBorder(null);
        descTextArea.setColumns(20);
        descTextArea.setLineWrap(true);
        descTextArea.setRows(5);
        descTextArea.setText(org.openide.util.NbBundle.getMessage(ConFiNFTPanel.class, "ConFiNFTPanel.descTextArea.text")); // NOI18N
        jScrollPane1.setViewportView(descTextArea);

        org.openide.awt.Mnemonics.setLocalizedText(jXButton1, org.openide.util.NbBundle.getMessage(ConFiNFTPanel.class, "ConFiNFTPanel.jXButton1.text")); // NOI18N

        imageView.setMaximumSize(new java.awt.Dimension(180, 180));
        imageView.setMinimumSize(new java.awt.Dimension(180, 180));
        imageView.setPreferredSize(new java.awt.Dimension(180, 180));

        javax.swing.GroupLayout imageViewLayout = new javax.swing.GroupLayout(imageView);
        imageView.setLayout(imageViewLayout);
        imageViewLayout.setHorizontalGroup(
            imageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imageViewLayout.setVerticalGroup(
            imageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(idLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(platformLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(imageView, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(platformLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTextArea descTextArea;
    private org.jdesktop.swingx.JXLabel idLbl;
    private org.jdesktop.swingx.JXImageView imageView;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXLabel nameLbl;
    private org.jdesktop.swingx.JXLabel platformLbl;
    // End of variables declaration//GEN-END:variables
}
