package com.acuilab.bc.main.wallet;

import com.acuilab.bc.main.nft.INFT;
import com.acuilab.bc.main.nft.MetaData;
import com.acuilab.bc.main.ui.WrapLayout;
import java.awt.FlowLayout;
import java.math.BigInteger;
import java.util.List;
import javax.swing.SwingWorker;
import org.javatuples.Pair;
import org.jdesktop.swingx.JXPanel;
import org.netbeans.api.progress.ProgressHandle;

/**
 *
 * @author admin
 */
public class NFTPanel extends JXPanel {
    private final Wallet wallet;
    private final INFT nft;
    
    /**
     * Creates new form NFTPanel
     */
    public NFTPanel(Wallet wallet, INFT nft) {
	initComponents();
	setLayout(new WrapLayout(FlowLayout.CENTER, 10, 10));
	
	this.wallet = wallet;
	this.nft = nft;
    }
    
    // 重新加载nft列表(后台线程执行)
    public void reload() {
        final ProgressHandle ph = ProgressHandle.createHandle("正在NFT列表，请稍候");
        SwingWorker<Void, Pair<Integer, MetaData>> worker = new SwingWorker<Void, Pair<Integer, MetaData>>() {
            @Override
            protected Void doInBackground() throws Exception {
                BigInteger[] tockens = nft.tokensOf(wallet.getAddress());
                ph.start(tockens.length);
                for(int i=0; i<tockens.length; i++) {
                    MetaData metaData = nft.getMetaData(tockens[i]);
                    
                    publish(Pair.with(i, metaData));
                }

                return null;
            }

            @Override
            protected void process(List<Pair<Integer, MetaData>> chunks) {
                for(Pair<Integer, MetaData> chunk : chunks) {
		    try {
			NFTPanel.this.add(new ConFiNFTPanel(chunk.getValue1()));
		    } catch (Exception ex) {
		    }
                    ph.progress(chunk.getValue0()+1);
                }
            }

            @Override
            protected void done() {
                ph.finish();
            }
        };
        worker.execute();
	
//	for (BigInteger tokenId : tockens) {
//	    try {
//		MetaData metaData = nft.getMetaData(tokenId);
//		// TODO: 根据metadata创建不同的panel
//		this.add(new ConFiNFTPanel(metaData));
//	    } catch (Exception ex) {
//	    }
//	}
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setScrollableHeightHint(org.jdesktop.swingx.ScrollableSizeHint.PREFERRED_STRETCH);
        setScrollableWidthHint(org.jdesktop.swingx.ScrollableSizeHint.PREFERRED_STRETCH);
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
