package com.acuilab.bc.main.wallet;

import com.acuilab.bc.main.nft.INFT;
import com.acuilab.bc.main.nft.MetaData;
import com.acuilab.bc.main.ui.WrapLayout;
import java.awt.FlowLayout;
import java.math.BigInteger;
import org.jdesktop.swingx.JXPanel;

/**
 *
 * @author admin
 */
public class NFTPanel extends JXPanel {
    private final Wallet wallet;
    private final INFT nft;
    
    /**
     * Creates new form NFTPanel
     */
    public NFTPanel(Wallet wallet, INFT nft) {
	initComponents();
	setLayout(new WrapLayout(FlowLayout.CENTER, 10, 10));
	
	this.wallet = wallet;
	this.nft = nft;
    }
    
    // 重新加载nft列表
    public void reload() {
	BigInteger[] tockens = nft.tokensOf(wallet.getAddress());
	
	for (BigInteger tokenId : tockens) {
	    try {
		MetaData metaData = nft.getMetaData(tokenId);
		System.out.println(metaData);
		// TODO: 根据metadata创建不同的panel
		this.add(new ConFiNFTPanel(metaData));
	    } catch (Exception ex) {
	    }
	}
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setScrollableHeightHint(org.jdesktop.swingx.ScrollableSizeHint.PREFERRED_STRETCH);
        setScrollableWidthHint(org.jdesktop.swingx.ScrollableSizeHint.PREFERRED_STRETCH);
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
