package com.acuilab.bc.main.wallet.wizard;

import com.google.common.collect.Maps;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.util.List;
import java.util.Map;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.ServiceUI;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Copies;
import javax.print.attribute.standard.JobName;
import javax.print.attribute.standard.MediaPrintableArea;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JLabel;
import javax.swing.JPanel;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.examples.complete.Utils;
import net.java.balloontip.utils.TimingUtils;
import org.apache.commons.lang3.StringUtils;
import org.openide.util.Exceptions;
import party.loveit.bip44forjava.utils.Bip44Utils;

public final class MnemonicGenerateVisualPanel extends JPanel {
    
    private List<String> mnemonicWords;
    
    /**
     * Creates new form FirstCreateVisualPanel3
     */
    public MnemonicGenerateVisualPanel() {
        initComponents();
        try {
            //get 12 words
            mnemonicWords = Bip44Utils.generateMnemonicWords();
            this.mnemonicLbl1.setText(mnemonicWords.get(0));
            this.mnemonicLbl2.setText(mnemonicWords.get(1));
            this.mnemonicLbl3.setText(mnemonicWords.get(2));
            this.mnemonicLbl4.setText(mnemonicWords.get(3));
            this.mnemonicLbl5.setText(mnemonicWords.get(4));
            this.mnemonicLbl6.setText(mnemonicWords.get(5));
            this.mnemonicLbl7.setText(mnemonicWords.get(6));
            this.mnemonicLbl8.setText(mnemonicWords.get(7));
            this.mnemonicLbl9.setText(mnemonicWords.get(8));
            this.mnemonicLbl10.setText(mnemonicWords.get(9));
            this.mnemonicLbl11.setText(mnemonicWords.get(10));
            this.mnemonicLbl12.setText(mnemonicWords.get(11));
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }
    
    public List<String> getMnemonicWords() {
        return mnemonicWords;
    }

    @Override
    public String getName() {
        return "生成您的助记词";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        mnemonicLbl1 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl2 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl3 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl4 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl5 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl6 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl7 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl8 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl9 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl10 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl11 = new org.jdesktop.swingx.JXLabel();
        mnemonicLbl12 = new org.jdesktop.swingx.JXLabel();
        copyBtn = new org.jdesktop.swingx.JXButton();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        printBtn = new org.jdesktop.swingx.JXButton();

        setMinimumSize(new java.awt.Dimension(760, 540));
        setPreferredSize(new java.awt.Dimension(760, 540));

        org.openide.awt.Mnemonics.setLocalizedText(jXLabel1, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.jXLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jXLabel2, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.jXLabel2.text")); // NOI18N

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jXPanel1.setLayout(new java.awt.GridLayout(4, 3, 10, 10));

        mnemonicLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n1-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl1, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl1.text")); // NOI18N
        jXPanel1.add(mnemonicLbl1);

        mnemonicLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n2-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl2, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl2.text")); // NOI18N
        jXPanel1.add(mnemonicLbl2);

        mnemonicLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n3-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl3, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl3.text")); // NOI18N
        jXPanel1.add(mnemonicLbl3);

        mnemonicLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n4-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl4, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl4.text")); // NOI18N
        jXPanel1.add(mnemonicLbl4);

        mnemonicLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n5-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl5, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl5.text")); // NOI18N
        jXPanel1.add(mnemonicLbl5);

        mnemonicLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n6-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl6, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl6.text")); // NOI18N
        jXPanel1.add(mnemonicLbl6);

        mnemonicLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n7-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl7, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl7.text")); // NOI18N
        jXPanel1.add(mnemonicLbl7);

        mnemonicLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n8-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl8, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl8.text")); // NOI18N
        jXPanel1.add(mnemonicLbl8);

        mnemonicLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n9-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl9, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl9.text")); // NOI18N
        jXPanel1.add(mnemonicLbl9);

        mnemonicLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n10-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl10, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl10.text")); // NOI18N
        jXPanel1.add(mnemonicLbl10);

        mnemonicLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n11-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl11, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl11.text")); // NOI18N
        jXPanel1.add(mnemonicLbl11);

        mnemonicLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/n12-32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mnemonicLbl12, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.mnemonicLbl12.text")); // NOI18N
        jXPanel1.add(mnemonicLbl12);

        org.openide.awt.Mnemonics.setLocalizedText(copyBtn, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.copyBtn.text")); // NOI18N
        copyBtn.setToolTipText(org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.copyBtn.toolTipText")); // NOI18N
        copyBtn.setDefaultCapable(false);
        copyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBtnActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jXLabel3, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.jXLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(printBtn, org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.printBtn.text")); // NOI18N
        printBtn.setToolTipText(org.openide.util.NbBundle.getMessage(MnemonicGenerateVisualPanel.class, "MnemonicGenerateVisualPanel.printBtn.toolTipText")); // NOI18N
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(copyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void copyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBtnActionPerformed
        Transferable str = new StringSelection(StringUtils.join(mnemonicWords, " ")); 
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str, null);
        
        // 气泡提示
        try {
            JLabel lbl = new JLabel("复制成功");
            BalloonTip balloonTip = new BalloonTip(copyBtn, 
                            lbl,
                            Utils.createBalloonTipStyle(),
                            Utils.createBalloonTipPositioner(), 
                            null);
            TimingUtils.showTimedBalloon(balloonTip, 2000);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_copyBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed

        PrintRequestAttributeSet pras = new HashPrintRequestAttributeSet();
        DocFlavor flavor = DocFlavor.SERVICE_FORMATTED.PRINTABLE;
        PrintService printService[] = PrintServiceLookup.lookupPrintServices(flavor, pras);//用户可选用的PrintService实例数组。
        PrintService defaultService = PrintServiceLookup.lookupDefaultPrintService(); //默认的PrintService 
        /*为用户提供一个选择 PrintService（打印机）的对话框。
            gc - 用于选择屏幕。null 意味着主屏幕或默认屏幕。
            x - 对话框在屏幕坐标中的位置，包括边框
            y - 对话框在屏幕坐标中的位置，包括边框
            services - 可浏览的服务，必须不为 null。
            defaultService - 要显示的初始 PrintService。
            flavor - 要打印的 flavor，或者为 null。
            attributes - 输入时为应用程序最初提供的首选项。这不能为 null，但可以为空。输出时为反映用户所作的更改的属性。
        */ 
        PrintService service = ServiceUI.printDialog(null, 200, 200,printService, defaultService, flavor, pras);
        if (service != null) {
            try {
                // create a print job for the chosen service
                DocPrintJob job = service.createPrintJob();
                PrintRequestAttributeSet aset = new HashPrintRequestAttributeSet();
                aset.add(OrientationRequested.PORTRAIT);
                aset.add(new Copies(1));
                aset.add(new JobName("Mnemonic print job", null));
                aset.add(new MediaPrintableArea(0, 0, 240, 480, MediaPrintableArea.MM));
                job.print(new SimpleDoc(new Printable() {
                    @Override
                    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                        if(pageIndex < 1) {
                            // 助记词二维码图像
                            String mnemonic = StringUtils.join(mnemonicWords, " ");
                            try {  
                                Map hints = Maps.newHashMap();  
                                hints.put(EncodeHintType.CHARACTER_SET, "UTF-8");  
                                hints.put(EncodeHintType.MARGIN, 0);  
                                BitMatrix byteMatrix = new MultiFormatWriter().encode(mnemonic, BarcodeFormat.QR_CODE, 128, 128, hints);
                                BufferedImage image = MatrixToImageWriter.toBufferedImage(byteMatrix);
                                // @see http://blog.163.com/laowu_000/blog/static/47198890200962144032793/
                                // 360*360dpi，约相当于1毫米14像素，宽24*14=336，高50*14=700
                                Graphics2D g2d = (Graphics2D) graphics;
//                                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                                g2d.drawImage(image, 10, 20, 128, 128, null);

                                g2d.setColor(Color.black);
                                g2d.setFont(new Font("宋体", Font.BOLD, 7));
                                g2d.drawString(mnemonic, 10, 10);

                                return Printable.PAGE_EXISTS;
                            } catch (WriterException ex) {
                                Exceptions.printStackTrace(ex);
                            }
                        }
                        
                        return Printable.NO_SUCH_PAGE;
                    }
                    
                }, flavor, null), aset);
            } catch (PrintException ex) {
                Exceptions.printStackTrace(ex);
            }
        }
    }//GEN-LAST:event_printBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton copyBtn;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXLabel mnemonicLbl1;
    private org.jdesktop.swingx.JXLabel mnemonicLbl10;
    private org.jdesktop.swingx.JXLabel mnemonicLbl11;
    private org.jdesktop.swingx.JXLabel mnemonicLbl12;
    private org.jdesktop.swingx.JXLabel mnemonicLbl2;
    private org.jdesktop.swingx.JXLabel mnemonicLbl3;
    private org.jdesktop.swingx.JXLabel mnemonicLbl4;
    private org.jdesktop.swingx.JXLabel mnemonicLbl5;
    private org.jdesktop.swingx.JXLabel mnemonicLbl6;
    private org.jdesktop.swingx.JXLabel mnemonicLbl7;
    private org.jdesktop.swingx.JXLabel mnemonicLbl8;
    private org.jdesktop.swingx.JXLabel mnemonicLbl9;
    private org.jdesktop.swingx.JXButton printBtn;
    // End of variables declaration//GEN-END:variables
}
